# Generated by Django 5.2.3 on 2025-06-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='linkedin_url',
            new_name='company_linkedin_url',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='product_url',
            new_name='user_linkedin_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_document', to=settings.AUTH_USER_MODEL)),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_document', to='users.productservice')),
            ],
        ),
    ]
