# Generated by Django 5.2.3 on 2025-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_linkedin_url_customuser_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='product_usp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductDocument',
        ),
    ]
