# Generated by Django 5.2.3 on 2025-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_productservice_product_usp_delete_productdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='product_url',
            field=models.URLField(null=True),
        ),
    ]
