# Generated by Django 5.2.3 on 2025-06-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supportrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
