# Generated by Django 5.2.3 on 2025-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_supportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
