# Generated by Django 5.2.3 on 2026-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
