# Generated by Django 5.2.3 on 2026-02-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
