# Generated by Django 5.2.3 on 2026-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_razorpaycreditorder_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
