# Generated by Django 5.2.3 on 2026-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_company_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='credits',
            field=models.IntegerField(default=50),
        ),
    ]
