# Generated by Django 5.2.3 on 2026-05-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0038_usersearchlimit_search_credits_and_more'),
        ('users', '0014_alter_userwallet_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='sent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='generate_email.sentemail'),
        ),
    ]
