# Generated by Django 5.2.3 on 2026-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_activitylog_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of emails this user is allowed to send. Default is 50.', verbose_name='Email Send Limit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_prospect_access',
            field=models.BooleanField(default=True, help_text='If enabled, this user can access the Prospect & Enrich feature. Uncheck to restrict new users until manually approved by admin.', verbose_name='Prospect & Enrich Access'),
        ),
    ]
