# Generated by Django 5.2.3 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_email_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_prospect_access',
            field=models.BooleanField(default=False, help_text='If enabled, this user can access the Prospect & Enrich feature. Uncheck to restrict new users until manually approved by admin.', verbose_name='Prospect & Enrich Access'),
        ),
    ]
