# Generated by Django 5.2.3 on 2025-06-20 05:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('message_id', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('opened', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('receiver_first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('receiver_last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('receiver_linkedin_url', models.URLField(blank=True, null=True)),
                ('selected_service', models.CharField(max_length=255, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('framework', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
