# Generated by Django 5.2.3 on 2025-06-16 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('receiver_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('framework', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('opened', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_email', to=settings.AUTH_USER_MODEL)),
                ('target_audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_email', to='generate_email.targetaudience')),
            ],
        ),
    ]
