# Generated by Django 5.2.3 on 2025-06-20 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generate_email', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='target_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_email', to='generate_email.targetaudience'),
        ),
    ]
