# Generated by Django 5.2.3 on 2025-06-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetaudience',
            old_name='linkedin_url',
            new_name='company_linkedin_url',
        ),
        migrations.RenameField(
            model_name='targetaudience',
            old_name='receiver_name',
            new_name='receiver_first_name',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='company_name',
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='receiver_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='selected_service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
