# Generated by Django 5.2.3 on 2025-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0002_rename_linkedin_url_targetaudience_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='message_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
