# Generated by Django 5.2.3 on 2025-06-23 06:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('message_id', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('opened', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_email', to='generate_email.sentemail')),
                ('target_audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_email', to='generate_email.targetaudience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
