# Generated by Django 5.2.3 on 2025-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0003_reminderemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderemail',
            name='send_at',
            field=models.DateField(),
        ),
    ]
