# Generated by Django 5.2.3 on 2025-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0004_alter_reminderemail_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='stop_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
