# Generated by Django 5.2.3 on 2025-06-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0005_sentemail_stop_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetaudience',
            name='company_linkedin_url',
        ),
    ]
