# Generated by Django 5.2.3 on 2025-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0006_remove_targetaudience_company_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='threadId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
