# Generated by Django 5.2.3 on 2026-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0008_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
