# Generated by Django 5.2.3 on 2026-01-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0009_sentemail_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
