# Generated by Django 5.2.3 on 2026-01-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0010_sentemail_open_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentemail',
            old_name='open_count',
            new_name='opened_count',
        ),
    ]
