# Generated by Django 5.2.3 on 2026-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0011_rename_open_count_sentemail_opened_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
    ]
