# Generated by Django 5.2.3 on 2026-01-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0012_sentemail_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemail',
            name='attachment',
        ),
    ]
