# Generated by Django 5.2.3 on 2026-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0013_remove_sentemail_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='sent_attachments/'),
        ),
    ]
