# Generated by Django 5.2.3 on 2026-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0014_sentemail_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemail',
            name='attachment',
        ),
    ]
