# Generated by Django 5.2.3 on 2026-02-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0015_remove_sentemail_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='clicked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='replied_count',
            field=models.IntegerField(default=0),
        ),
    ]
