# Generated by Django 5.2.3 on 2026-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0016_sentemail_clicked_count_sentemail_replied_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaudience',
            name='campaign_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='framework',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='selected_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
