# Generated by Django 5.2.3 on 2026-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0016_sentemail_clicked_count_sentemail_replied_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='tags',
            field=models.ManyToManyField(blank=True, to='generate_email.tag'),
        ),
    ]
