# Generated by Django 5.2.3 on 2026-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0017_tag_targetaudience_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
