# Generated by Django 5.2.3 on 2026-02-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0018_sentemail_is_sent_sentemail_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetaudience',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sentemail',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='sentemail',
            name='send_at',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
