# Generated by Django 5.2.3 on 2026-02-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0020_audiencetag_targetaudience_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
