# Generated by Django 5.2.3 on 2026-02-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0022_sentemail_sending_account'),
        ('users', '0012_razorpaycreditorder_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.emailattachment'),
        ),
    ]
