# Generated by Django 5.2.3 on 2026-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0023_sentemail_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='shuffle_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='campaign_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='framework',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='selected_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
