# Generated by Django 5.2.3 on 2026-03-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0017_alter_targetaudience_campaign_goal_and_more'),
        ('generate_email', '0024_sentemail_shuffle_accounts_and_more'),
    ]

    operations = [
    ]
