# Generated by Django 5.2.3 on 2026-03-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0025_merge_20260309_1407'),
        ('generate_email', '0025_merge_20260309_1421'),
    ]

    operations = [
    ]
