# Generated by Django 5.2.3 on 2026-03-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0026_merge_20260317_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPeopleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavedCompanyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('revenue', models.CharField(blank=True, max_length=255)),
                ('specialties', models.TextField(blank=True)),
                ('headquarter', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company_market', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_entries', to='generate_email.savedpeoplelist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPeopleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=100)),
                ('last', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('company_website', models.URLField(blank=True, max_length=500)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company_headquarter', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='generate_email.savedpeoplelist')),
            ],
            options={
                'unique_together': {('saved_list', 'linkedin')},
            },
        ),
    ]
