# Generated by Django 5.2.3 on 2026-03-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0029_searchhistory_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('people', 'People Search'), ('company', 'Company Search'), ('linkedin', 'LinkedIn Search')], max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Search Log',
                'verbose_name_plural': 'Global Search Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
