# Generated by Django 5.2.3 on 2026-03-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0031_usersearchlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchlimit',
            name='credits',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
