# Generated by Django 5.2.3 on 2026-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0034_enrichmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrequest',
            name='credits_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
