# Generated by Django 5.2.3 on 2026-03-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0035_enrichmentrequest_credits_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrequest',
            name='enrich_type',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
