# Generated by Django 5.2.3 on 2026-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0036_enrichmentrequest_enrich_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchlimit',
            name='credits',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
