# Generated by Django 5.2.3 on 2026-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0037_alter_usersearchlimit_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchlimit',
            name='search_credits',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='usersearchlimit',
            name='credits',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
