# Generated by Django 5.2.3 on 2026-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0038_usersearchlimit_search_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpeopleentry',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
