# Generated by Django 5.2.3 on 2026-05-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0040_enrichmentjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(blank=True, null=True)),
                ('contact_names', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_results',
            },
        ),
    ]
