# Generated by Django 5.2.3 on 2026-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0041_taskresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderemail',
            name='send_at',
            field=models.DateTimeField(),
        ),
    ]
