# Generated by Django 5.2.3 on 2026-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0042_alter_reminderemail_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
