# Generated by Django 5.2.3 on 2026-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0043_sentemail_replied_sentemail_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='is_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
