# Generated by Django 5.2.5 on 2026-06-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0044_sentemail_is_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
