# Generated by Django 5.2.5 on 2026-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0045_sentemail_bounced_sentemail_bounced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='campaign_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
