"""
Django settings for saleswithai project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 
ALLOWED_HOSTS = ['fairly-whole-hawk.ngrok-free.app','localhost','sellsmart-dvdhbme5h6eud4hz.centralindia-01.azurewebsites.net','www.sellsharp.co', 'sellsharp.co','20.192.98.161', '127.0.0.1']
MS_GRAPH_CLIENT_STATE = "superSecret123jms"
SITE_ID = 1

SITE_URL = "https://sellsharp.co"

RAZORPAY_KEY_ID="rzp_live_SC3leksBzXMUTY"
RAZORPAY_KEY_SECRET="5wHpeUYjmXZCKbiRMbA8LR0p"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'storages',
    'users',
    'generate_email',
    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'django_celery_beat',
    'frontend',
]

SOCIALACCOUNT_PROVIDERS = {

    'google': {

        'AUTH_PARAMS': {
            'prompt': 'consent',
            "access_type": "offline",

        },
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/gmail.send',  # Add this line

        ],
    },
    'microsoft': {

        'SCOPE': [
            'User.Read',
            'Mail.Send',  # 👈 Needed to send email
            'offline_access',
            'openid',
            'profile',
            'email',
            'Mail.ReadWrite',
        ],
        'AUTH_PARAMS': {
            'response_type': 'code',
            'prompt': 'select_account'
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'saleswithai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# # --------------------------------------------------
# # MEDIA FILES (LOCAL + AZURE BLOB)
# # --------------------------------------------------

# USE_AZURE_MEDIA = os.environ.get("USE_AZURE_MEDIA", "0").lower() in ("1", "true")

# if USE_AZURE_MEDIA:
#     # ===== AZURE BLOB STORAGE (PRODUCTION) =====
#     AZURE_ACCOUNT_NAME = os.environ["AZURE_ACCOUNT_NAME"]
#     AZURE_ACCOUNT_KEY = os.environ["AZURE_ACCOUNT_KEY"]
#     AZURE_CONTAINER = os.environ.get("AZURE_MEDIA_CONTAINER", "media")

#     AZURE_CUSTOM_DOMAIN = os.environ.get(
#         "AZURE_CUSTOM_DOMAIN",
#         f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net",
#     )

#     DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"

#     MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/"

#     STORAGES = {
#         "default": {
#             "BACKEND": "storages.backends.azure_storage.AzureStorage",
#         },
#         "staticfiles": {
#             "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#         },
#     }

# else:
#     # ===== LOCAL FILESYSTEM (DEVELOPMENT) =====
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = os.path.join(BASE_DIR, "media")

#     STORAGES = {
#         "default": {
#             "BACKEND": "django.core.files.storage.FileSystemStorage",
#         },
#         "staticfiles": {
#             "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#         },
#     }

# --------------------------------------------------
# MEDIA FILES – AZURE BLOB (HARD CODED)
# --------------------------------------------------

# --------------------------------------------------
# MEDIA FILES (LOCAL vs AZURE - AUTO SWITCH)
# --------------------------------------------------

if DEBUG:
    # =====================
    # LOCAL MEDIA (DEV)
    # =====================
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

else:
    # =====================
    # AZURE BLOB (PROD)
    # =====================
    MEDIA_URL = "https://sellsharpstorage.blob.core.windows.net/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.environ["AZURE_ACCOUNT_NAME"],
                "account_key": os.environ["AZURE_ACCOUNT_KEY"],
                "azure_container": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }


WSGI_APPLICATION = 'saleswithai.wsgi.application'

CSRF_TRUSTED_ORIGINS = ['https://sellsmart-dvdhbme5h6eud4hz.centralindia-01.azurewebsites.net']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


else:
    CONNECTION_STRING = os.environ['AZURE_POSTGRESQL_CONNECTIONSTRING']
    conn_str_params = {pair.split('=')[0]: pair.split('=')[1] for pair in CONNECTION_STRING.split(' ')}
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': conn_str_params['dbname'],
            'HOST': conn_str_params['host'],
            'USER': conn_str_params['user'],
            'PASSWORD': conn_str_params['password'],
        }
    }
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.CustomUser'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/home/site/wwwroot/static/staticfiles"



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
DEFAULT_FROM_EMAIL = f"Sales with AI <{os.environ['EMAIL_HOST_USER']}>"
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = os.environ['SENDGRID_API']
# DEFAULT_FROM_EMAIL = f"Sales with AI <nikita@jmsadvisory.in>"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

LOGIN_REDIRECT_URL = '/users/profile/'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'
ACCOUNT_LOGOUT_REDIRECT_URL = 'login'  # Redirect URL after logout
ACCOUNT_USERNAME_REQUIRED = False  # Disable username requirement
ACCOUNT_USER_MODEL_USERNAME_FIELD = None # tell allauth there's no 'username'
ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_EMAIL_REQUIRED = True  # Email is required
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_STORE_TOKENS = True
ACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapters.MySocialAccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True

# Reminders
# CELERY_BROKER_URL = 'rediss://:4JPY7Oj7e46UQ6OhMOUCX9zIREi8FdXaoAzCaFrSqdI%3D@salesredis.redis.cache.windows.net:6380/0'
# CELERY_BROKER_USE_SSL = True
# CELERY_BROKER_USE_SSL = {
#     'ssl_cert_reqs': None
# }
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Kolkata'
# CELERY_ENABLE_UTC = True
#
# CELERY_BEAT_SCHEDULE = {
#     'send-reminder-emails': {
#         'task': 'generate_email.tasks.send_reminders',
#         # 'schedule': crontab(minute=0, hour=12),   # every day at 12:00 PM (noon)
#         'schedule': crontab(minute='*')
#     },
# }
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'



#log file
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': '/home/site/wwwroot/django_errors.log',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'users': {
                'handlers': ['file'],
                'level': 'DEBUG',
                'propagate': False,
            },
        },

    }